### ISSUE TITLE
Unpredicted StatusCode.DEADLINE_EXCEEDED-Deadline Exceeded

### ISSUE THREAD

**Issue by imZEH** [openvinotoolkit/model_server#1365]
I encountered several times regarding this kind of error message.
What I did was doing 100 request at a time. It actually works for several tries. But for some scenario it will suddenly return this kind of error .

I implemented this syntax to run asynchronously but I think it failed me.
```
result_future = self.stub.Predict.future(self.request)
response = result_future.result()
```

My setup are
OVMS server has 4 cores, setup 4 workers and nireq=32.

**Comment by mzegla** [comment]
Did you try setting `timeout` parameter?
https://grpc.github.io/grpc/python/grpc.html#multi-callable-interfaces
Also, you might consider not sending all 100 request at once, but let's say, in batches of 20 and after every 20 requests, read responses.

**Comment by imZEH** [comment]
> 

Thank you for the response @mzegla 

yeah, I applied it lately. Just realize it took so long when using the default value. Does the value of 10.0 timeout would be enough ?

On the OVMS side, How would I setup my device If it has 4 cores ? 
Would you think 20 request is the max request at a time base on the cores ?
Does setting CPU_THROUGHPUT_STREAMS to 2 would suffice or set it to AUTO ?

**Comment by mzegla** [comment]
It depends on how long it takes for OVMS to process the request and it varies depending on the model you use, hardware you have, networking overhead etc.
Try with different timeout values and see what will be enough in your environment.

When it comes to OVMS configuration. Do you use latest OVMS - 2022.1? 
If so, instead of using `CPU_THROUGHPUT_STREAMS` you can try with `PERFORMANCE_HINT`.
It takes one of two values: `LATENCY` or `THROUGHPUT` and adjusts the model to optimize for one of these metrics. 

For 4 cores it seems that there's no point in having more than 1 stream, so I think in your case this setting will be almost identical for both latency and throughput optimization. Setting streams manually to 2 seems like a bad idea for a 4 cores CPU. 
As far as I know optimal way is having 1 CPU Stream per 4 physical cores and having to many streams compared to the amount of cores will most likely decrease performance. 

I hope it's not too messy and you don't get confused. When you try to figure out the best configuration for your model served in OVMS you can try benchmark client that will utilize the model to the fullest and give you information on what kind of numbers you can expect:

https://github.com/openvinotoolkit/model_server/tree/main/demos/benchmark/cpp

**Comment by imZEH** [comment]
Thank you for the suggestions.
I'll try to setup those things and observe.
For OVMS , Currently I installed OVMS 2021.4.2.
