### ISSUE TITLE
using openvino server in async mode 

### ISSUE THREAD

**Issue by DanilKonon** [openvinotoolkit/model_server#278]
I have one model which I want to use maximally on my CPU (8 cores). 

`sudo docker run -d -v /home/open_vino_model:/models/detection_model/1  -e LOG_LEVEL=DEBUG -p 9000:9000 openvino/ubuntu18_model_server  /ie-serving-py/start_server.sh ie_serving model --model_path /models/detection_model --model_name detection_model --port 9000  --shape auto --grpc_workers 25 --rest_workers 25  --nireq 10  --plugin_config "{\"CPU_THROUGHPUT_STREAMS\": \"5\", \"CPU_THREADS_NUM\": \"10\"}"
`

I don't understand how can I speed up this most efficiently. Because right now this command without any parameters specification gives me about 2.1 fps. While all the variants I try are maximum 1.5 or less. 

`sudo docker run -d -v /home/open_vino_model:/models/detection_model/1  -e LOG_LEVEL=DEBUG -p 9000:9000 openvino/ubuntu18_model_server  /ie-serving-py/start_server.sh ie_serving model --model_path /models/detection_model --model_name detection_model --port 9000  --shape auto`

How to use model server in maximally async mode and get the most performance gain?

**Comment by mzegla** [comment]
Hi, are those 8 cores physical or virtual cores?
How do you generate traffic? Do you send one request at a time or multiple requests in parallel?

**Comment by DanilKonon** [comment]
Hi! 
To generate traffic I use: 
`python face_detection.py --batch_size 2 --input_images_dir /data/ --height 640 --width 640  --output_dir ./results`

As I understand I have 4 real cores and 8 cpus associated with them.

**Comment by mzegla** [comment]
It seems correct that when using command without parameters you get better performance. Looking at the way you send requests it seems it's the best configuration. Without parameters OVMS starts with one server thread and one CPU Stream and that's all you can utilize simply using single face_detection.py client. 

It's because face_detection.py sends requests synchronously, so OVMS cannot process for example 2 images at the same time because it gets requests one by one. So even though you specified grpc_workers, nireq and CPU streams numer to be more than 1, your client doesn't take advantage of it and you end up with even worse performance than when you run model server with single thread and CPU Stream.

Either way, OpenVINO uses only physical cores and from my experience, it "divides" physical cores into streams of 4, so I would say for your setup 1 stream is optimal and setting this numer to higher (you set 5) will be nonoptimal. To me it looks like setting `--plugin_config` causes performance difference between the two variants you posted.

I would recommend:
- using default plugin config,
- modifying client application to send multiple requests at a time (in multiple threads or processes)
- setting grpc_workers and nireq to numer at least as big as number of "requests senders" from previous point

You can also see what is max performance your setup can get by using desired model directly with OpenVINO (for example with benchmark app - https://docs.openvinotoolkit.org/latest/_inference_engine_tools_benchmark_tool_README.html)

**Comment by DanilKonon** [comment]
So I want to use rabbitmq queue to send requests. As I understand, it solves the problem of sending request synchronously.  Then all I need is somehow asynchronously get maximum throughput? Do you know where can I read more about this?

**Comment by DanilKonon** [comment]
I wrote some python code with Pool to get messages from rabbitmq queue and send them to serving model. So now I set number of processes, number of grace workers and nireq to 5. It works, but I don't get very big performance speedup. Still can't get higher than 2 fps. Thank you!

**Comment by mzegla** [comment]
Could you run benchmark app I've mentioned earlier? It should tell you what's the max performance OpenVINO can provide. If your hardware can get no more than 2 FPS, then there's nothing that can be done in model server. 
If you get bigger numbers on benchmark app, then it would mean that serving is the bottleneck.

**Comment by DanilKonon** [comment]
Yes, I ran benchmark app. It gave me 2 FPS. Am I right to understand, that benchmark app gives best results, and I cannot tweak parameters somehow to get better performance?

**Comment by brmarkus** [comment]
Depending on your used CPU you might benefit from using the AVX512-VNNI CPU instruction set by converting your used model to use INT8 precission.
Depending on your used model and input resolution you might want to reshape your model to not need to use scaling.

**Comment by mzegla** [comment]
As @brmarkus  said, you can try optimizing your model. 
From model server point of view, numbers you get from benchmark app is theoretical max for model server and there's no tuning in OVMS that would let you beat benchmark app performance.

**Comment by DanilKonon** [comment]
ok, thank you very much. I will try to use INT8 precision.

**Comment by brmarkus** [comment]
Can you maybe comment on your requirements?
Do you HAVE TO use the ModelServer (using Google-RPC and ProtoBuf, which could introduce latencies)?
Do you need to consider latencies introduced by loading the image(s)? Maybe replace loading images via OpenCV and use TurboJPG instead?
Do you use single pictures from picture files (JPG, PNG, BMP, etc) or frames from a video/IP-camera, which you would need to decode first? Are you sure you are using HW-accelerated video decoding? Can you optimize the data-flow from where you get the video (like USB, using DMA, like iso-chronous data-transfer), using "GPU_nocopy", using libdrm and "primefd"?
Do you use "nested models", i.e. the output of one model would need to be fed into a next model (e.g. first finding a face with model A, then using model B to find the facial landmarks within that face defined by a RegionOfInterest), which often requires "ping-pong-calls" between your client and the ModelServer. Then I would prefer using an e.g. standalone C++ application instead.

There are several measures to optimize "everything outside the inference".

**Comment by DanilKonon** [comment]
1. I get image urls and need to load them to get numpy arrays of them. and then resize them with opencv.
2. I use ssd net from tensorflow object detection api (so no multi nested models and ping-pong)

**Comment by brmarkus** [comment]
If you need to load "lots of images" (and buffer/queue them) then maybe try this: https://www.learnopencv.com/efficient-image-loading/
For me, using "TurboJpeg" worked best.

Sounds like your main concern is the latency introduced by the inference in ModellServer.

**Comment by brmarkus** [comment]
When you say 

> load them to get numpy arrays of them. and then resize them with opencv

would maybe this, `https://github.com/opencv/openvino_training_extensions/issues/320#issuecomment-648190168`, work for you, i.e. reshape the input tensor to accept your original image resolution, and then 

> You will avoid resize function, and inference of model will be faster.

It also mentions `https://github.com/opencv/openvino_training_extensions/issues/320#issuecomment-648249071`, 

> Also you can fine tune model on target resolution

**Comment by DanilKonon** [comment]
1. All my images have different input resolutions. So I need to reshape each one to 640 on 640 image size.
2. I use this line to load images. I don't think that TurboJpeg can work with any image extension. What if it is PNG image?
`image = Image.open(urllib.request.urlopen(body_json["ImageUrl"])).convert('RGB')`

**Comment by rasapala** [comment]
@DanilKonon let us know if you need any more help in this thread.
