### ISSUE TITLE
Graceful shutdown - GRPC port stays in use

### ISSUE THREAD

**Issue by jhagege** [openvinotoolkit/model_server#716]
Hi, when doing stress test on OVMS server, we have found some cases where the GRPC port is still being allocated even after killing the OVMS process, sometimes for 30s-1min. 
Is it a known behavior ? Is there a way to force port to get cleaned when shutting down the process with a kill signal in Unix? 

Thanks.

**Comment by mzegla** [comment]
Hi, do you kill OVMS when it's still processing requests? If so, then to me it looks like expected behavior.
The client-server connection is not freed immediately after one of the sides wants to finish it and the TCP connection is still on for a while to prevent delayed requests from being received by the next application that uses the same port. That's why sometimes server might occupy the port for a bit longer to make sure everything is closed properly before freeing it.

We don't modify that behavior in our tests, but I found something like this:

> On Linux systems the TIMED-WAIT state is a kernel value. tcp/sys/net/ipv4/tcp_fin_timeout is where this kernel value is stored.
> 
> To update the current setting:
> echo 30 > /proc/sys/net/ipv4/tcp_fin_timeout
> 
> To view the current setting:
> cat /proc/sys/net/ipv4/tcp_fin_timeout

So you can try that (it might require rebuilding docker image with such modification in place), but I have no idea if this will work for you.

**Comment by jhagege** [comment]
> Hi, do you kill OVMS when it's still processing requests? If so, then to me it looks like expected behavior.
> The client-server connection is not freed immediately after one of the sides wants to finish it and the TCP connection is still on for a while to prevent delayed requests from being received by the next application that uses the same port. That's why sometimes server might occupy the port for a bit longer to make sure everything is closed properly before freeing it.
> 
> We don't modify that behavior in our tests, but I found something like this:
> 
> > On Linux systems the TIMED-WAIT state is a kernel value. tcp/sys/net/ipv4/tcp_fin_timeout is where this kernel value is stored.
> > To update the current setting:
> > echo 30 > /proc/sys/net/ipv4/tcp_fin_timeout
> > To view the current setting:
> > cat /proc/sys/net/ipv4/tcp_fin_timeout
> 
> So you can try that (it might require rebuilding docker image with such modification in place), but I have no idea if this will work for you.

Thanks much for your quick reply, this is very helpful.
