### ISSUE TITLE
ubuntu images is pulled automatically instead of centos

### ISSUE THREAD

**Issue by ParthM-GitHub** [openvinotoolkit/model_server#953]
Hi There,
I am trying to clone 2021.4 and 2021.4.1 tags on OpenVINO AMI. After performing sudo make docker_build command. ubuntu 20.04 image is automatically pulled instead of centos image, and due to this I am unable run build.sh file. It throws the error "yum command not found".
And also one more thing, in the build.sh file line no 20. BASE_OS variable. It is BASE_OS=${3:=centos}. It should be BASE_OS=${3:-centos}. This problem has been there for a longtime. 
More importantly please help me with Issue#1 wrong image pull issue, that's more pressing. And just for temporary workaround, can you please tell which centos tag image I should manually pull from docker repo. I will manually pull the image as a workaround.
Thanks.

**Comment by ParthM-GitHub** [comment]
For some reason, it's now pulling the correct CentOS docker image. So, the main issue is resolved.
But FYI - there is still a small issue in build.sh file as described. Which is minor thus, I am closing this issue.

**Comment by dtrawins** [comment]
@ParthM-GitHub Starting from version 2021.4.1 the public image of the model server is based on ubuntu instead of centos. For now you could still build the image based on centos using a command `make docker_build BASE_OS=centos` . 
Have in mind that we plan to discontinue the image version based on centos. There will be available option to use the image based on ubuntu (published on dockerhub) and redhat UBI (published in redhat ecosystem catalog).
I assume you are referring to [extras/nginx-mtls-auth/build.sh](../blob/main/extras/nginx-mtls-auth/build.sh)
Indeed we need to change its default baseos to ubuntu and fix the assignment syntax.
Thank you for reporting it.
